version: "3.9"
services:
  starrocks-fe-0:
    image: starrocks/fe-ubuntu:latest
    hostname: starrocks-fe-0
    container_name: starrocks-fe-0
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/fe_entrypoint.sh starrocks-fe-0
    environment:
      - HOST_TYPE=FQDN
      - TZ=Asia/Shanghai
    ports:
      - "1030:8030"
      - "2020:9020"
      - "3030:9030"
    volumes:
       - 1fe3be_fe0_data:/opt/starrocks/fe/meta

  starrocks-be-0:
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-0
    container_name: starrocks-be-0
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0
    environment:
      - HOST_TYPE=FQDN
      - TZ=Asia/Shanghai
    depends_on:
      - starrocks-fe-0
    volumes:
      - 1fe3be_be0_data:/opt/starrocks/be/storage

  starrocks-be-1:
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-1
    container_name: starrocks-be-1
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0
    environment:
      - HOST_TYPE=FQDN
      - TZ=Asia/Shanghai
    depends_on:
      - starrocks-fe-0
    volumes:
      - 1fe3be_be1_data:/opt/starrocks/be/storage

  starrocks-be-2:
    image: starrocks/be-ubuntu:latest
    hostname: starrocks-be-2
    container_name: starrocks-be-2
    command:
      - /bin/bash
      - -c
      - |
        /opt/starrocks/be_entrypoint.sh starrocks-fe-0
    environment:
      - HOST_TYPE=FQDN
      - TZ=Asia/Shanghai
    depends_on:
      - starrocks-fe-0
    volumes:
      - 1fe3be_be2_data:/opt/starrocks/be/storage

volumes:
  1fe3be_fe0_data:
  1fe3be_be0_data:
  1fe3be_be1_data:
  1fe3be_be2_data:
